# Generated by Django 4.0.3 on 2022-03-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelebotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the person that using this bot', max_length=1000)),
                ('join_date', models.DateTimeField(help_text='Date when user started to use bot')),
                ('sending_status', models.BooleanField(help_text='True if user wants to get messages from this bot about changes in exchange rate')),
            ],
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='dollar_rate',
            field=models.FloatField(help_text='Dollar exchange rate', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='euro_rate',
            field=models.FloatField(help_text='Euro exchange rate', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangedata',
            name='time_rate',
            field=models.DateTimeField(help_text='Time when rate was obtained'),
        ),
    ]
