# Generated by Django 4.0.3 on 2022-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0002_telebotusers_alter_exchangedata_dollar_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telebotusers',
            name='percent_user',
            field=models.IntegerField(default=5, help_text='Percents that user wants to use in check_rate'),
        ),
    ]
