# Generated by Django 4.0.3 on 2022-03-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0003_telebotusers_percent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telebotusers',
            name='user_currency',
            field=models.CharField(default='dollar_rate', help_text='Currencies that user selected for automessages', max_length=1000),
        ),
    ]
