# Generated by Django 4.0.3 on 2022-03-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0004_telebotusers_user_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedata',
            name='yen_rate',
            field=models.FloatField(default=0.84, help_text='Yen exchange rate', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangedata',
            name='yuan_rate',
            field=models.FloatField(default=16.02, help_text='Yuan exchange rate', max_length=10),
            preserve_default=False,
        ),
    ]
