# Generated by Django 4.0.3 on 2022-04-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0006_userpreviousmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreviousmessages',
            name='previous_rate',
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='dollar_prev',
            field=models.FloatField(default=1, help_text='Dollar rate that previously was sent to user', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='euro_prev',
            field=models.FloatField(default=1, help_text='Euro rate that previously was sent to user', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='yen_prev',
            field=models.FloatField(default=1, help_text='Yen rate that previously was sent to user', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='yuan_prev',
            field=models.FloatField(default=1, help_text='Yuan rate that previously was sent to user', max_length=10),
            preserve_default=False,
        ),
    ]
