# Generated by Django 4.0.3 on 2022-04-03 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0007_remove_userpreviousmessages_previous_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreviousmessages',
            name='time_dollar',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when dollar was recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='time_euro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when euro was recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='time_yen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when yen was recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreviousmessages',
            name='time_yuan',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when yuan was recorded'),
            preserve_default=False,
        ),
    ]
