# Generated by Django 4.0.3 on 2022-04-04 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0009_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='feedback_send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time when feedback was recorded'),
            preserve_default=False,
        ),
    ]
