# Generated by Django 4.0.3 on 2022-04-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0010_userfeedback_feedback_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebotusers',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 17, 54), help_text='Date when user started to use bot'),
        ),
        migrations.AlterField(
            model_name='telebotusers',
            name='percent_user',
            field=models.FloatField(default=5, help_text='Percents that user wants to use in check_rate'),
        ),
        migrations.AlterField(
            model_name='telebotusers',
            name='sending_status',
            field=models.BooleanField(default=False, help_text='True if user wants to get messages from this bot about changes in exchange rate'),
        ),
    ]
